export const COPY = {
  auth: {
    login_title: "はじめる",
    login_button: "かいしゃに入る",
    join_with_code: "招待コードで入る",
    company_code_label: "会社のコード（必須）",
    name_label: "なまえ（必須）",
  },
  nav: {
    home: "ホーム",
    reports: "日報",
    tasks: "進みぐあい",
    personnel: "人員ボード",
    search: "探す",
    settings: "じぶんの設定",
  },
  report: {
    create: "日報を書く",
    generate: "日報をつくる",
    send: "事務所に送る",
    saved: "下書きをのこす",
    voice_hint: "マイクをおして、話してね",
    text_hint: "またはここに書いてね",
    site_label: "現場（必須）",
    name_label: "なまえ（必須）",
    site_select_placeholder: "現場をえらんでね",
  },
  task: {
    today: "今日のしごと",
    add_quantity_quick: "+1 / +5 / +10 で増やせるよ",
    enter_quantity: "数値で入れる",
    completed_message: "おわった！おつかれさま",
    interrupt_title: "なぜとめた？",
    status: {
      not_started: "まだ",
      in_progress: "やってる",
      paused: "とまってる",
      completed: "おわった",
    },
    pause_reasons: {
      rain: "雨",
      material: "材料まち",
      manpower: "人手たりない",
      other: "そのほか",
    },
  },
  shift: {
    day_full: "日勤・1日",
    day_am: "日勤・午前",
    day_pm: "日勤・午後",
    night_full: "夜勤・1晩",
    night_early: "夜勤・前半",
    night_late: "夜勤・後半",
  },
  shift_short: {
    day_full: "日勤",
    day_am: "日勤AM",
    day_pm: "日勤PM",
    night_full: "夜勤",
    night_early: "夜勤前半",
    night_late: "夜勤後半",
  },
  assignment: {
    board_title: "だれでも見れる人員ボード",
    week_subtitle: "1週間×現場で、だれがいるか一目でわかります",
    change_button: "急に変更する",
    acknowledge: "了解しました",
    add_to_cell: "ここに人を入れる",
    no_one: "まだいない",
    today_changed: "当日に変更あり",
    personal_view: "じぶんの今週",
    site_view: "現場ごと",
    week_view: "1週間で見る",
  },
  site: {
    overall_progress: "現場ぜんたいのすすみぐあい",
    change_progress: "進みぐあいを変える",
    progress_comment_placeholder: "ひとこと（例：基礎工事が完了。来週から内装に入る）",
    today_workers: "今日いる人",
    no_workers_today: "今日はまだ決まってない",
  },
  search: {
    title: "探す",
    placeholder: "例: 雨天 / 中断 / 不具合",
    suggest_title: "よく探されてる",
    tag_title: "タグから探す",
    no_results: "まだ見つかりません",
  },
  worker: {
    home_greeting: (name: string) => `おはよう、${name}さん`,
    today_site: "きょうの現場",
    today_tasks: "きょうのしごと",
    photo_status: "状況を写真でしらせる",
    quick_status: {
      started: "はじめた",
      half: "半分くらい",
      almost: "あと少し",
      done: "おわった",
    },
  },
  supervisor: {
    home_greeting: (name: string) => `おはよう、${name}さん`,
    my_sites: "担当現場",
    today_attendance: "今日の人員",
    correct_qty: "数値を直す",
  },
  admin: {
    dashboard_title: "ダッシュボード",
    today_summary: "今日の状況サマリ",
    urgent_actions: "急ぎの対応",
    recent_photos: "直近の現場写真",
  },
  common: {
    save: "ほぞんする",
    cancel: "やめる",
    confirm: "これでOK",
    back: "もどる",
    loading: "読みこみ中…",
    empty: "まだありません",
    error_default: "うまくいかなかった。もう一回ためしてね",
    required_note: "（必須）= かならず入れてね",
  },
} as const;

export const SHIFT_LABEL = COPY.shift;
export const SHIFT_LABEL_SHORT = COPY.shift_short;
export const TASK_STATUS_LABEL = COPY.task.status;
export const PAUSE_REASON_LABEL = COPY.task.pause_reasons;
