export const COPY = {
  auth: {
    login_title: "ログイン",
    login_button: "ログイン",
    join_with_code: "招待コードで入る",
    company_code_label: "会社コード（必須）",
    name_label: "氏名（必須）",
  },
  nav: {
    home: "ホーム",
    reports: "日報",
    tasks: "進捗",
    personnel: "人員ボード",
    search: "探す",
    settings: "設定",
  },
  report: {
    create: "日報作成",
    generate: "日報を生成",
    send: "送信",
    saved: "下書き保存",
    voice_hint: "マイクボタンを押して音声入力",
    text_hint: "テキストで入力",
    site_label: "現場（必須）",
    name_label: "氏名（必須）",
    site_select_placeholder: "現場を選択",
  },
  task: {
    today: "本日の作業",
    add_quantity_quick: "+1 / +5 / +10 で実績を加算",
    enter_quantity: "数値入力",
    completed_message: "完了しました",
    interrupt_title: "中断理由",
    status: {
      not_started: "未着手",
      in_progress: "作業中",
      paused: "中断中",
      completed: "完了",
    },
    pause_reasons: {
      rain: "雨",
      material: "材料まち",
      manpower: "人員不足",
      other: "そのほか",
    },
  },
  shift: {
    day_full: "日勤・1日",
    day_am: "日勤・午前",
    day_pm: "日勤・午後",
    night_full: "夜勤・1晩",
    night_early: "夜勤・前半",
    night_late: "夜勤・後半",
  },
  shift_short: {
    day_full: "日勤",
    day_am: "日勤AM",
    day_pm: "日勤PM",
    night_full: "夜勤",
    night_early: "夜勤前半",
    night_late: "夜勤後半",
  },
  assignment: {
    board_title: "人員ボード",
    week_subtitle: "1週間×現場で配置を一覧",
    change_button: "急変更",
    acknowledge: "確認しました",
    add_to_cell: "ここに配置",
    no_one: "未配置",
    today_changed: "本日変更あり",
    personal_view: "自分の今週",
    site_view: "現場別",
    week_view: "週次",
  },
  site: {
    overall_progress: "現場全体の進捗",
    change_progress: "進捗を更新",
    progress_comment_placeholder: "コメント（例：基礎工事完了。来週から内装へ）",
    today_workers: "本日の出勤者",
    no_workers_today: "未定",
  },
  search: {
    title: "探す",
    placeholder: "例: 雨天 / 中断 / 不具合",
    suggest_title: "よく探されてる",
    tag_title: "タグから探す",
    no_results: "まだ見つかりません",
  },
  worker: {
    home_greeting: (name: string) => `おはよう、${name}さん`,
    today_site: "きょうの現場",
    today_tasks: "きょうのしごと",
    photo_status: "状況を写真でしらせる",
    quick_status: {
      started: "はじめた",
      half: "半分くらい",
      almost: "あと少し",
      done: "おわった",
    },
  },
  supervisor: {
    home_greeting: (name: string) => `おはよう、${name}さん`,
    my_sites: "担当現場",
    today_attendance: "本日の人員",
    correct_qty: "数値を補正",
  },
  admin: {
    dashboard_title: "ダッシュボード",
    today_summary: "今日の状況サマリ",
    urgent_actions: "急ぎの対応",
    recent_photos: "直近の現場写真",
  },
  common: {
    save: "保存",
    cancel: "キャンセル",
    confirm: "決定",
    back: "戻る",
    loading: "読み込み中…",
    empty: "データがありません",
    error_default: "処理に失敗しました。再度お試しください",
    required_note: "（必須）の項目は入力必須です",
  },
} as const;

export const SHIFT_LABEL = COPY.shift;
export const SHIFT_LABEL_SHORT = COPY.shift_short;
export const TASK_STATUS_LABEL = COPY.task.status;
export const PAUSE_REASON_LABEL = COPY.task.pause_reasons;
